version: "3.9"

services:
  postgres:
    restart: always

    image: postgres:14.4-alpine3.16

    ports:
      - 5431:5432

    volumes:
      - db-ecommerce:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  ecommerce:
    build: .

    restart: always

    ports:
      - 8000:8000

    volumes:
      - .:/app

    depends_on:
      - postgres
      
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}

volumes:
  db-ecommerce: